## Part 1


1.   Define function,
2.   define vector A,
3.   reshape to matrix, (read out shape)
4.   concatenate with another vector, (and, perhaps, another with product of the first two)
5.   assign one of its rows/columns to new values,
6.   define another vector b and solve linear equation, (includes: look up function online, see why it fails)
7.   solve normal equation A^T A x = A^T b (matrix multiplication (np.matmul and @), transpose)


## Solutions 1

In [1]:
import numpy as np

# 1.
def f(x):
  return x**2
print(f(1), f(2), f(3))

# 2.
A = np.random.random_sample(100)
print(A.shape)

# 3.
A = np.reshape(A, (-1, 1))
print(A.shape)

# 4.
v = np.ones((100, 1))
print(v.shape)
A = np.concatenate([A, v], axis=1)
print(A.shape)

# 5.
A[:50, 1] = np.random.random_sample(50)
print(A[47:53, :])

# 4. continued
print(A[:, 0].shape)
print(A[:, 0:1].shape)
A = np.concatenate([A, A[:, 0:1]*A[:, 1:2]], axis=1)
print(A.shape)

# 6
b = np.random.random_sample((100, 1))
print(b.shape)
# TODO: google linalg solve
# x = np.linalg.solve(A, b)  # doesn't work!


# 7
rhs = np.transpose(A) @ b
lhs = np.transpose(A) @ A
print(rhs.shape)
print(lhs.shape)
x = np.linalg.solve(lhs, rhs)
print(x)

1 4 9
(100,)
(100, 1)
(100, 1)
(100, 2)
[[0.38271783 0.68090357]
 [0.27576094 0.23862666]
 [0.194007   0.43043475]
 [0.65276724 1.        ]
 [0.0968355  1.        ]
 [0.28672392 1.        ]]
(100,)
(100, 1)
(100, 3)
(100, 1)
(3, 1)
(3, 3)
[[ 0.73445932]
 [ 0.69941219]
 [-1.06094221]]


## Part 2



8. Define linear funtion f(x) = ax + b from R^3 to R
9. Monte Carlo estimation of L^1 error between f(x) and g(x) for two functions f, g and x uniform on [0, 1]^3
10.  Monte Carlo estimate E[g(X)]
11.  Assign subset of x vector where x>=0.5 to a new value
12.  Identity matrix and scaling matrices with constants.
13.  Rebuild some matrix A from its SVD np.linalg.svd



## Solutions 2

In [2]:
# 8.
a = np.random.random_sample(3)
b = np.random.random_sample()
print(a.shape)

def f(x):
  return np.sum(a*x) + b


x = np.ones(3)
print(f(x))
x = np.ones((10, 3))
print(f(x))  # not what we want: We want 10 values...

def f_vec(x):
  return np.sum(a*x, axis=1) + b  # numpy automatically treats a as containing as many rows as x, and multiplies elementwise

print(f_vec(x))

# 9.
def g_vec(x):
  return np.sin(x[:, 0]) + np.cos(x[:, 1]) + x[:, 2]

x = np.random.random_sample([10000, 3])
fx = f_vec(x)
gx = g_vec(x)
diff = np.abs(fx-gx)
print(diff.shape)
mcest = np.mean(diff)
print(mcest)

# 10.
print(np.mean(gx))

# 11
print((x > 0.5).shape)
print(x[x > 0.5].shape)
x[x > 0.5] = np.ones_like(x[x>0.5])
print(x.shape)
print(x)

# 12.
id = np.identity(5)
print(id)
id_scale = 0.1 * id
print(id_scale)

(3,)
2.053725333086098
16.532051696128285
[2.05372533 2.05372533 2.05372533 2.05372533 2.05372533 2.05372533
 2.05372533 2.05372533 2.05372533 2.05372533]
(10000,)
0.6034499066181104
1.7957057954952769
(10000, 3)
(14868,)
(10000, 3)
[[0.45237685 1.         1.        ]
 [0.05987436 1.         0.46402295]
 [1.         0.45629178 1.        ]
 ...
 [0.22813719 0.40875586 1.        ]
 [0.0105602  0.09385298 1.        ]
 [1.         0.07355713 0.3326094 ]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.1 0.  0.  0.  0. ]
 [0.  0.1 0.  0.  0. ]
 [0.  0.  0.1 0.  0. ]
 [0.  0.  0.  0.1 0. ]
 [0.  0.  0.  0.  0.1]]


In [3]:
# 13.
A = np.random.random_sample([3, 2])
print(A)
U, S, Vh = np.linalg.svd(A, full_matrices=False)
print(U.shape, S.shape, Vh.shape)
S = np.diag(S)
print(S.shape)
print(S)
A_rec = U@S@Vh
print(np.sum(np.abs(A_rec-A)))

[[0.99748231 0.54180705]
 [0.87467905 0.08614947]
 [0.987354   0.0642632 ]]
(3, 2) (2,) (2, 2)
(2, 2)
[[1.70642686 0.        ]
 [0.         0.35793301]]
2.7755575615628914e-17
